^(.iqy|.bqy).*(View|RowFolder)=[^&\x3b]*<\s*script
User-Agent\x3a\x20[^\n]*WinHttp\x2eWinHttpRequest.*\n
ping\x7c\d+\x7c.+\x7c\d\x7c\d\x7c.+\x7c
^Sin[^\r\n]*\/[^\r\n]*\x0D\x0A\d+\x0D\x0A
^connected\x2e[^\x0D\x0A]*20\d\d[^\x0D\x0A]*ver\x3A\s+Legends\s2\x2e1
^[^\n]*filename[^\x3B]*([\x5C\x2F]\x2E\x2E|\x2E\x2E[\x5C\x2F])
keyword\x3d[^\r\n]*url\x3d[^\r\n]*www\x252efindthewebsiteyouneed\x252ecom
^X-OEM\x3A[^\r\n]*iOpus\s+Software\s+GmbH.*X-Sender\x3A[^\r\n]*iOpus\s+Software\s+GmbH
^Host\x3A[^\r\n]*sda\x2Eedonkey\x2Ecom.*User-Agent\x3A[^\r\n]*ed2k
^ServerDetails\x7c[^\r\n]*\x7c[^\r\n]*\x7c
toStaticHtml\s*\x28[^\x29]*<\s*style\s*>.*[&\x22<>]\s*\w+[\x3a=].*\x29\x3b
index\.php\?.*mail=[^\r\n\x26]*\x3C\x3F
IP\x3A\s+[^\r\n]*\x0d\x0aOS\x3A\s+[^\r\n]*
^URL\x3b\w+\x3amailto\x3a[^\n]*%[^\n]*\.(cmd|bat)
default.idq[^\r\n]*ciRestriction[^\r\n]*script
\/oaboard[^\r\n]*\/forum\.php[^\r\n]*[\x26\x3F]inc\x3Dhttp\x3A\x2F
^Subject\x3a[^\r\n]*Report[^\r\n]*from[^\r\n]*ChildWebGuardian
^User-Agent\x3A[^\r\n]*snprtz\x7Cdialno.*Host\x3A[^\r\n]*www\x2Eotherchance\x2Ecom
(mailto|telnet|news|nntp|snews)\x3A[^\n]*\x25[^\n]*\x22\x2Ecmd
(mailto|telnet|news|nntp|snews)\x3A[^\n]*\x25[^\n]*\x22\x2Ebat
^From\x3a\xd0\xc5\xcf\xa2.*Subject\x3a[^\r\n]*\d+\x2d\d+\x2d\d+\x2d\d+\x3a\d+\x3a\d+
^Subject\x3a[^\r\n]*Beyond\s+Keylogger\s+Report\x2E\s+Id\x3d\x5b.*\x5d
<link[^\x3e]*href\s*\=[^\x3e]*javascript\x3a
\x7B[^\x7B]*position\s*\x3A\s*absolute[^\x7D]*\x7D
